services:
  - type: web
    name: chat_line
    env: python
    region: Singapore  # หรือ frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python chat_line.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # ให้กำหนดค่าใน Render Dashboard เอง
      - key: LINE_ACCESS_TOKEN
        sync: false
      - key: PORT
        value: 5000  # ค่าเริ่มต้น
